# Generated by Django 3.2 on 2021-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
