# Generated by Django 3.2 on 2021-04-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], null=True),
        ),
    ]
